name: Coordinates
version: '${project.version}'
main: org.dqc.coordinates.Coordinates
api-version: '1.20'
commands:
  coordenadas:
    description: Mostra as coordenadas ao jogador
    usage: /coordenadas
